Repository FACG6/UNOPS, pull requests merged in 2019-04, with the labels that each got.

#20 File structure, server & dependencies
  .eslintrc.json
  .gitignore
  .travis.yml
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  package-lock.json
  package.json
  server/app.js
  server/index.js
  test/server.test.js
Labels: approved

#51 Update the app to render a browser router
  .gitignore
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.jsx
  client/src/index.js
Labels: approved, urgent

#56 Create the logo component
  client/src/components/Logo/index.jsx
  client/src/logo.svg
Labels: approved

#46 Create the main sidebar component
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/style.css
  client/src/App.jsx
  client/src/components/MainSidebar/index.jsx
  client/src/components/MainSidebar/style.css
  client/src/logo.svg
Labels: approved

#49 Login component
  client/.eslintrc.json
  client/.gitignore
  client/src/App.jsx
  client/src/components/Login/index.jsx
  client/src/components/Login/style.css
Labels: approved

#57 remove .env file
  client/.env
  client/.gitignore
Labels: approved, bug, urgent

#58 add .env to be ignored in github
  client/.gitignore
Labels: approved, bug, urgent

#59 New ticket component
  client/public/index.html
  client/public/style.css
  client/src/App.jsx
  client/src/components/NewTicket/index.jsx
  client/src/components/NewTicket/style.css
Labels: awaiting review

#66 Readme
  README.md
Labels: awaiting review, urgent

#52 add ticketSidbar component with style
  client/src/App.jsx
  client/src/components/TicketsSidebar/index.jsx
  client/src/components/TicketsSidebar/style.css
Labels: approved

#64 Replies component
  client/src/App.jsx
  client/src/components/Conversation/index.jsx
  client/src/components/Conversation/style.css
  client/src/components/Replies/index.jsx
  client/src/components/Replies/style.css
Labels: approved

#61 Wrapped tickets
  client/.eslintrc.json
  client/public/index.html
  client/src/App.jsx
  client/src/components/WrappedTicket/index.jsx
  client/src/components/WrappedTicket/style.css
Labels: changes requested

#60 Anchors component
  client/package-lock.json
  client/public/index.html
  client/src/App.css
  client/src/App.jsx
  client/src/components/Homepage/index.jsx
  client/src/components/Homepage/style.css
  client/src/components/Homepage/tickets-home-all.jsx
  client/src/components/Homepage/tickets-home-draft.jsx
  client/src/components/Homepage/tickets-home-my.jsx
  client/src/components/Homepage/tickets-home-trash.jsx
  client/src/components/MainSidebar/style.css
  client/src/components/NewTicket/NewTicketForm.jsx
  client/src/components/NewTicket/index.jsx
  client/src/components/NewTicket/style.css
  client/src/components/buttons/buttons.jsx
  client/src/components/navbar/Navbar.jsx
  client/src/components/navbar/style.css
  client/src/components/opened-ticket/index.jsx
  client/src/components/opened-ticket/style.css
  client/src/components/reports/Report.jsx
  client/src/components/reports/index.jsx
  client/src/components/reports/style.css
  client/src/components/search/Sidebar.jsx
  client/src/components/search/index.jsx
  client/src/components/search/style.css
  package-lock.json
Labels: approved

#62 Component open tickets
  client/src/components/NewTicket/style.css
  client/src/components/OpenTicket/ContentLogo/index.jsx
  client/src/components/OpenTicket/ContentLogo/style.css
  client/src/components/OpenTicket/ContentSubject/index.jsx
  client/src/components/OpenTicket/ContentSubject/style.css
  client/src/components/OpenTicket/TheReply/index.jsx
  client/src/components/OpenTicket/TheReply/style.css
  client/src/components/OpenTicket/index.jsx
  client/src/components/OpenTicket/style.css
Labels: approved

#72 delete unnecessary components and add the logo and main sidebar
  client/src/components/Conversation/index.jsx
  client/src/components/Conversation/style.css
  client/src/components/Homepage/index.jsx
  client/src/components/Homepage/style.css
  client/src/components/Homepage/tickets-home-all.jsx
  client/src/components/Homepage/tickets-home-draft.jsx
  client/src/components/Homepage/tickets-home-my.jsx
  client/src/components/Homepage/tickets-home-trash.jsx
  client/src/components/Login/index.jsx
  client/src/components/Login/style.css
  client/src/components/Logo/index.jsx
  client/src/components/MainSidebar/index.jsx
  client/src/components/NewTicket/NewTicketForm.jsx
  client/src/components/NewTicket/index.jsx
  client/src/components/NewTicket/style.css
  client/src/components/OpenTicket/ContentLogo/index.jsx
  client/src/components/OpenTicket/ContentLogo/style.css
  client/src/components/OpenTicket/ContentSubject/index.jsx
  client/src/components/OpenTicket/ContentSubject/style.css
  client/src/components/OpenTicket/TheReply/index.jsx
  client/src/components/OpenTicket/TheReply/style.css
  client/src/components/OpenTicket/index.jsx
  client/src/components/OpenTicket/style.css
  client/src/components/Replies/index.jsx
  client/src/components/Replies/style.css
  client/src/components/TicketsSidebar/index.jsx
  client/src/components/TicketsSidebar/style.css
  client/src/components/WrappedTicket/index.jsx
  client/src/components/WrappedTicket/style.css
  client/src/components/buttons/buttons.jsx
  client/src/components/navbar/Navbar.jsx
  client/src/components/navbar/style.css
  client/src/components/opened-ticket/index.jsx
  client/src/components/opened-ticket/style.css
  client/src/components/parts/Logo/index.jsx
  client/src/components/parts/MainSidebar/index.jsx
  client/src/components/parts/MainSidebar/style.css
  client/src/components/parts/Navbar/index.jsx
  client/src/components/parts/Navbar/style.css
  client/src/components/reports/Report.jsx
  client/src/components/reports/index.jsx
  client/src/components/reports/style.css
  client/src/components/search/Sidebar.jsx
  client/src/components/search/index.jsx
  client/src/components/search/style.css
Labels: approved

#73 Add the second sidebars, create the wrapped ticket component
  client/src/components/parts/SearchSidebar/index.jsx
  client/src/components/parts/SearchSidebar/style.css
  client/src/components/parts/TicketsSidebar/index.jsx
  client/src/components/parts/TicketsSidebar/style.css
  client/src/components/parts/WrappedTicket/index.jsx
  client/src/components/parts/WrappedTicket/style.css
Labels: Frontend, approved

#74 create the opened ticket components for viewing single tickets
  client/src/App.jsx
  client/src/components/parts/EmailCopy/index.jsx
  client/src/components/parts/OpenedTicket/index.jsx
  client/src/components/parts/OpenedTicket/style.css
  client/src/components/parts/Replies/index.jsx
  client/src/components/parts/Replies/style.css
  client/src/components/parts/Reply/index.jsx
  client/src/components/parts/Reply/style.css
  client/src/components/parts/ReplyCard/index.jsx
  client/src/components/parts/ReplyCard/style.css
Labels: Frontend, approved

#75 created the new ticket components, and view its page
  client/src/components/pages/NewTicketPage/index.jsx
  client/src/components/pages/NewTicketPage/style.css
  client/src/components/parts/NewTicket/index.jsx
  client/src/components/parts/NewTicket/style.css
Labels: Frontend, approved

#76 created the main pages to render
  client/src/components/pages/Login/index.jsx
  client/src/components/pages/Login/style.css
  client/src/components/pages/SearchPage/index.jsx
  client/src/components/pages/SearchPage/style.css
  client/src/components/pages/TicketsPage/index.jsx
  client/src/components/pages/TicketsPage/style.css
Labels: Frontend, awaiting review

#78 add the routes to render the pages
  client/src/App.css
  client/src/App.jsx
  client/src/components/model.js
Labels: Frontend, awaiting review

#77 created the opened ticket page to be rendered
  client/src/components/pages/OpenedTicketPage/index.jsx
  client/src/components/pages/OpenedTicketPage/style.css
Labels: Frontend, awaiting review

#80 Opened ticket page
  client/src/components/pages/OpenedTicketPage/index.jsx
  client/src/components/pages/OpenedTicketPage/style.css
Labels: awaiting review

#81 Fix bugs and refactor code to follow eslint rules
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/model.js
  client/src/components/model.jsx
  client/src/components/pages/Login/index.jsx
  client/src/components/pages/NewTicketPage/index.jsx
  client/src/components/pages/OpenedTicketPage/index.jsx
  client/src/components/pages/SearchPage/index.jsx
  client/src/components/pages/TicketsPage/index.jsx
  client/src/components/parts/EmailCopy/index.jsx
  client/src/components/parts/NewTicket/index.jsx
  client/src/components/parts/Replies/index.jsx
  client/src/components/parts/Reply/index.jsx
  client/src/components/parts/TicketsSidebar/index.jsx
  client/src/components/parts/WrappedTicket/index.jsx
  client/src/components/parts/WrappedTicket/style.css
Labels: awaiting review

#82 setup the imap and express servers
  server/index.js
Labels: awaiting review

#84 Database
  package.json
  server/database/build.js
  server/database/build.sql
  server/database/connection.js
Labels: approved

#85 created the database quiries
  server/database/build.sql
  server/database/connection.js
  server/database/quiries/getTickets.js
  server/database/quiries/getUserByEmail.js
Labels: approved

#83 Routes handling
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.jsx
  client/src/components/pages/TicketsPage/index.jsx
  package-lock.json
  package.json
  server/app.js
  server/authentication/authenticate.js
  server/authentication/cookie.js
  server/authentication/verifyCookie.js
  server/controllers/Imap-connection.js
  server/controllers/home.js
  server/controllers/index.js
  server/controllers/login.js
  server/controllers/newTicket.js
  server/controllers/reports.js
  server/controllers/search.js
  server/controllers/socket.js
  server/index.js
Labels: awaiting review
