Repository FACG6/UNOPS, pull requests merged in 2019-05, with the labels that each got.

#87 Handle fetches
  client/package-lock.json
  client/public/index.html
  client/src/App.jsx
  client/src/components/pages/SearchPage/index.jsx
  client/src/components/parts/SearchSidebar/index.jsx
  package.json
Labels: approved

#90 Fetch data
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/pages/TicketsPage/index.jsx
  client/src/components/pages/TicketsPage/style.css
  client/src/components/parts/OpenedTicket/index.jsx
  client/src/components/parts/WrappedTicket/index.jsx
  client/src/components/parts/WrappedTicket/style.css
  package-lock.json
  package.json
  server/app.js
  server/controllers/Imap-connection.js
  server/controllers/index.js
  server/controllers/socket.js
  server/index.js
Labels: approved, urgent

#91 send email and replies using nodemailer
  client/src/App.jsx
  server/controllers/nodemailer.js
  server/controllers/socket.js
  server/database/build.sql
  server/database/quiries/addTicket.js
  server/database/quiries/addreply.js
Labels: awaiting review

#98 send reply and get conversation
  client/src/App.jsx
  server/controllers/Imap-connection.js
  server/controllers/socket.js
Labels: approved

#97 Update app
  client/src/App.jsx
  client/src/components/pages/TicketsPage/index.jsx
  client/src/components/parts/WrappedTicket/index.jsx
  package-lock.json
  package.json
  server/app.js
Labels: approved

#99 Connection
  client/src/App.jsx
  client/src/components/parts/WrappedTicket/index.jsx
  package-lock.json
  package.json
  server/controllers/Imap-connection.js
Labels: awaiting review

#100 Fetch data
  client/src/App.jsx
  server/authentication/verifyCookie.js
  server/controllers/Imap-connection.js
  server/controllers/socket.js
Labels: in progress
